### ISSUE TITLE
代码不全呀

### ISSUE THREAD

**Issue by malatang20001210** [zqluo-buaa/ADRoadnet#2]
![image](https://github.com/user-attachments/assets/29ea648e-5a72-41a4-b7e3-959df2c6a127)
![image](https://github.com/user-attachments/assets/dff8cafa-9a70-4d2f-bada-8c1a70a47b03)

**Comment by zqluo-buaa** [comment]
The module "FirstSatgement_FE" is no longer used in the release version, and we have update the code to solve this problem.
